language: php
sudo: required
dist: trusty
group: edge
php:
 - hhvm
 - hhvm-nightly
 - hhvm-3.15
 - hhvm-3.12
install:
 - sudo apt-get update && sudo apt-get upgrade -y
 - sudo apt-get install -y openssl
 - composer install
script:
 - hh_client
 - hhvm vendor/bin/phpunit tests
